import { GuidanceChunkSchema, type GuidanceChunk } from "@/features/guidance/schema";

export const GUIDANCE_SNAPSHOT_VERSION = "engineering-resumes-2026-09-02";
const ROOT = "https://www.reddit.com/r/EngineeringResumes/wiki/index/";
const REVIEWED_AT = "2026-09-02";

function chunk(
  value: Omit<GuidanceChunk, "reviewedAt" | "applicability" | "mandatory" | "category" | "locale"> &
    Partial<Pick<GuidanceChunk, "applicability" | "mandatory" | "category" | "locale">>,
): GuidanceChunk {
  return GuidanceChunkSchema.parse({
    reviewedAt: REVIEWED_AT,
    applicability: "general",
    category: "global",
    locale: "general",
    mandatory: false,
    ...value,
  });
}

export const GUIDANCE_CORPUS: GuidanceChunk[] = [
  chunk({ id: "er-factual-evidence", title: "Use genuine evidence", guidance: "A resume can present real experience strategically, but it cannot replace missing experience. Never add an employer, credential, technology, result, or metric that the candidate did not supply.", sourceUrl: `${ROOT}#wiki_introduction`, sourceSection: "Introduction", tasks: ["analyze", "tailor", "proofread"], sections: ["global"], tags: ["facts", "evidence", "truth", "metrics", "technology"], mandatory: true }),
  chunk({ id: "er-relevant-content", title: "Prioritize relevant content", guidance: "Tailor the resume to the target role by moving the most relevant and impressive supported details earlier and removing content that does not strengthen the candidacy.", sourceUrl: `${ROOT}#wiki_general_rules`, sourceSection: "General Rules", tasks: ["analyze", "tailor"], sections: ["global"], tags: ["relevance", "job", "keywords", "order", "tailor"], mandatory: true }),
  chunk({ id: "er-single-column", title: "Use one readable column", guidance: "Prefer a straightforward single-column layout without icons, images, graphics, or decorative sidebars so people and parsing systems can follow the content in reading order.", sourceUrl: `${ROOT}#wiki_general_rules`, sourceSection: "General Rules", tasks: ["format"], sections: ["global"], tags: ["ats", "layout", "single column", "readability"] }),
  chunk({ id: "er-readable-type", title: "Keep type readable", guidance: "Use a modern, readable, sufficiently dark font at 10.5 points or larger. Avoid thin gray text and excessive italics, bold, or all caps.", sourceUrl: `${ROOT}#wiki_accessibility`, sourceSection: "Accessibility", tasks: ["format"], sections: ["global"], tags: ["font", "size", "contrast", "accessibility", "bold", "italics"] }),
  chunk({ id: "er-white-space", title: "Protect white space", guidance: "Keep margins at least 0.4 inches and use consistent space between sections and entries. Do not cram content merely to force a page count.", sourceUrl: `${ROOT}#wiki_accessibility`, sourceSection: "Accessibility", tasks: ["format", "tailor"], sections: ["global"], tags: ["margin", "spacing", "density", "white space"] }),
  chunk({ id: "er-page-length", title: "Use one page when appropriate", guidance: "Most early- and mid-career resumes should fit one page after irrelevant material is removed. A second page can be justified for candidates with roughly a decade or more of relevant experience or senior scope.", sourceUrl: `${ROOT}#wiki_keep_it_to_1_page`, sourceSection: "Keep it to 1 page", tasks: ["format", "tailor"], sections: ["global"], tags: ["page", "length", "senior", "experience"] }),
  chunk({ id: "er-section-separation", title: "Separate sections clearly", guidance: "Use recognizable section names and consistent visual separation so recruiters can locate experience, skills, projects, and education quickly.", sourceUrl: `${ROOT}#wiki_accessibility`, sourceSection: "Accessibility", tasks: ["format"], sections: ["global"], tags: ["sections", "headings", "spacing", "skim"] }),
  chunk({ id: "er-section-order-experienced", title: "Lead with professional evidence", guidance: "After graduation and once meaningful full-time experience exists, lead with Experience or Skills, keep the other close behind, and generally place Education later.", sourceUrl: `${ROOT}#wiki_section_order`, sourceSection: "Section Order", tasks: ["format", "tailor"], sections: ["global", "experience", "skills", "education"], tags: ["order", "experienced", "professional"] }),
  chunk({ id: "er-section-order-student", title: "Lead students with education or projects", guidance: "Students and new graduates may lead with Education; candidates without technical work should bring strong Projects before unrelated work and Skills.", sourceUrl: `${ROOT}#wiki_section_order`, sourceSection: "Section Order", tasks: ["format", "tailor"], sections: ["global", "projects", "education"], tags: ["order", "student", "graduate", "projects"] }),
  chunk({ id: "er-summary-conditional", title: "Use summaries selectively", guidance: "Omit a summary unless it clarifies senior or staff scope, a career change, or a material employment gap. Otherwise spend the space on evidence.", sourceUrl: `${ROOT}#wiki_section_order`, sourceSection: "Section Order", tasks: ["format", "tailor"], sections: ["global"], tags: ["summary", "headline", "senior", "career change"] }),
  chunk({ id: "er-contact-address", title: "Avoid a full street address", guidance: "Do not include a physical street address or postal code. A concise location is optional and most useful when it establishes relevance to the target location.", sourceUrl: `${ROOT}#wiki_contact_information`, sourceSection: "Contact Information", tasks: ["format", "tailor"], sections: ["contact"], tags: ["address", "location", "contact", "privacy"], applicability: "us-canada" }),
  chunk({ id: "er-contact-email", title: "Keep contact details direct", guidance: "Use one professional email address and display contact values directly without redundant labels such as Email, Phone, GitHub, or Portfolio.", sourceUrl: `${ROOT}#wiki_contact_information`, sourceSection: "Contact Information", tasks: ["format", "proofread"], sections: ["contact"], tags: ["email", "phone", "github", "portfolio", "labels"] }),
  chunk({ id: "er-contact-links", title: "Include useful links only", guidance: "Include a GitHub or portfolio link only when it contains material that strengthens the application. Keep displayed URLs concise and recognizable.", sourceUrl: `${ROOT}#wiki_contact_information`, sourceSection: "Contact Information", tasks: ["analyze", "tailor"], sections: ["contact"], tags: ["github", "portfolio", "url", "links"] }),
  chunk({ id: "er-experience-name", title: "Use a conventional experience heading", guidance: "Name the paid or research work section Experience or Work Experience so its meaning is immediately clear.", sourceUrl: `${ROOT}#wiki_work_experience`, sourceSection: "Work Experience", tasks: ["format"], sections: ["experience"], tags: ["experience", "heading", "ats"] }),
  chunk({ id: "er-experience-context", title: "Describe accomplishments with context", guidance: "Do not repeat a job description or stack buzzwords. Explain what was built or solved, how the work was done, and why the result mattered.", sourceUrl: `${ROOT}#wiki_work_experience`, sourceSection: "Work Experience", tasks: ["analyze", "tailor"], sections: ["experience", "bullets"], tags: ["accomplishment", "context", "impact", "technical"] }),
  chunk({ id: "er-technical-first", title: "Lead with technical substance", guidance: "For engineering roles, foreground the engineering decisions, constraints, validation, and outcomes; software or tools should support the story rather than replace it.", sourceUrl: `${ROOT}#wiki_work_experience`, sourceSection: "Work Experience", tasks: ["analyze", "tailor"], sections: ["experience", "projects", "bullets"], tags: ["engineering", "technical", "tools", "validation"] }),
  chunk({ id: "er-bullet-one-sentence", title: "Keep bullets concise", guidance: "Aim for one sentence and roughly one to two rendered lines per bullet. Split or trim bullets that become difficult to scan.", sourceUrl: `${ROOT}#wiki_bullet_points`, sourceSection: "Bullet Points", tasks: ["tailor", "proofread"], sections: ["bullets", "experience", "projects"], tags: ["bullet", "length", "sentence", "concise"] }),
  chunk({ id: "er-bullet-order", title: "Put the strongest bullets first", guidance: "Order bullets from the most relevant or impressive evidence to the least important because reviewers may read only the first few.", sourceUrl: `${ROOT}#wiki_bullet_points`, sourceSection: "Bullet Points", tasks: ["analyze", "tailor"], sections: ["bullets", "experience", "projects"], tags: ["bullet", "order", "relevance", "impact"] }),
  chunk({ id: "er-no-pronouns", title: "Remove personal pronouns", guidance: "Write resume bullets without personal pronouns such as I, we, us, my, or our.", sourceUrl: `${ROOT}#wiki_bullet_points`, sourceSection: "Bullet Points", tasks: ["tailor", "proofread"], sections: ["bullets"], tags: ["pronoun", "i", "we", "our", "style"] }),
  chunk({ id: "er-no-periods", title: "Use consistent bullet endings", guidance: "Resume bullets are fragments in this style guide, so omit terminal periods and apply that convention consistently.", sourceUrl: `${ROOT}#wiki_bullet_points`, sourceSection: "Bullet Points", tasks: ["proofread", "format"], sections: ["bullets"], tags: ["period", "punctuation", "consistency"] }),
  chunk({ id: "er-avoid-fillers", title: "Cut filler language", guidance: "Limit adjectives, adverbs, and inflated claims that consume space without adding technical evidence or outcomes.", sourceUrl: `${ROOT}#wiki_bullet_points`, sourceSection: "Bullet Points", tasks: ["tailor", "proofread"], sections: ["bullets"], tags: ["adjective", "adverb", "filler", "concise"] }),
  chunk({ id: "er-action-verbs", title: "Open with a precise action verb", guidance: "Begin bullets with a specific past-tense action verb such as built, designed, implemented, analyzed, reduced, automated, or optimized.", sourceUrl: `${ROOT}#wiki_action_verbs`, sourceSection: "Action Verbs", tasks: ["tailor", "proofread"], sections: ["bullets"], tags: ["action", "verb", "built", "designed", "implemented"] }),
  chunk({ id: "er-weak-verbs", title: "Replace weak opening verbs", guidance: "Avoid weak or vague openings such as helped, assisted, participated, used, utilized, worked on, coded, or gained experience.", sourceUrl: `${ROOT}#wiki_action_verbs`, sourceSection: "Action Verbs", tasks: ["tailor", "proofread"], sections: ["bullets"], tags: ["weak", "verb", "helped", "used", "worked"] }),
  chunk({ id: "er-star-car-xyz", title: "Connect action to result", guidance: "Use STAR, CAR, or XYZ thinking to connect the situation or challenge, the candidate's action, and the supported result without mechanically forcing every component into every bullet.", sourceUrl: `${ROOT}#wiki_each_bullet_point_should_follow_star.2C_xyz.2C_or_car`, sourceSection: "STAR, XYZ, or CAR", tasks: ["tailor"], sections: ["bullets", "experience", "projects"], tags: ["star", "car", "xyz", "action", "result", "challenge"] }),
  chunk({ id: "er-metrics-supported", title: "Quantify only supported outcomes", guidance: "When a genuine metric exists, place it near the important outcome. Never invent a number merely to satisfy a bullet formula.", sourceUrl: `${ROOT}#wiki_each_bullet_point_should_follow_star.2C_xyz.2C_or_car`, sourceSection: "STAR, XYZ, or CAR", tasks: ["tailor", "proofread"], sections: ["bullets"], tags: ["metric", "number", "quantify", "result", "evidence"] }),
  chunk({ id: "er-date-present", title: "Use Present consistently", guidance: "Use Present for an ongoing role or project rather than Current, Now, or Ongoing.", sourceUrl: `${ROOT}#wiki_dates`, sourceSection: "Dates", tasks: ["format", "proofread"], sections: ["dates"], tags: ["date", "present", "current", "ongoing"] }),
  chunk({ id: "er-date-format", title: "Keep date formats consistent", guidance: "Use full years, consistent month treatment, and an en dash with spaces for ranges. Do not mix seasons, numeric months, abbreviated years, or specific days.", sourceUrl: `${ROOT}#wiki_dates`, sourceSection: "Dates", tasks: ["format", "proofread"], sections: ["dates"], tags: ["date", "month", "year", "range", "dash"] }),
  chunk({ id: "er-skills-commas", title: "Keep skills compact", guidance: "Group relevant skills under clear labels and separate items with commas rather than progress bars, ratings, or decorative treatments.", sourceUrl: `${ROOT}#wiki_general_rules`, sourceSection: "General Rules", tasks: ["format", "tailor"], sections: ["skills"], tags: ["skills", "commas", "group", "rating"] }),
  chunk({ id: "er-keywords-context", title: "Use keywords in truthful context", guidance: "Include relevant job terminology where the resume evidence supports it, preferably inside accomplishment context rather than as an isolated keyword dump.", sourceUrl: `${ROOT}#wiki_make_your_resume_more_effective`, sourceSection: "Make your resume more effective", tasks: ["analyze", "tailor"], sections: ["skills", "experience", "projects"], tags: ["keyword", "job", "ats", "context", "technology"] }),
  chunk({ id: "er-projects-technical", title: "Show project engineering depth", guidance: "Project entries should demonstrate a problem, technical choices, validation, and results. Prefer a few substantive projects over a long list of shallow descriptions.", sourceUrl: `${ROOT}#wiki_projects`, sourceSection: "Projects", tasks: ["analyze", "tailor"], sections: ["projects", "bullets"], tags: ["project", "technical", "validation", "result"] }),
  chunk({ id: "er-education-relevance", title: "Keep education relevant", guidance: "Use Education prominently for students and new graduates, but reduce its prominence after substantial professional experience. Include details only when they support the target role.", sourceUrl: `${ROOT}#wiki_education`, sourceSection: "Education", tasks: ["analyze", "tailor", "format"], sections: ["education"], tags: ["education", "student", "graduate", "coursework", "order"] }),
];
