import type { GuidanceChunk } from "@/features/guidance/schema";

export const CAREER_STAGE_KNOWLEDGE: GuidanceChunk[] = [
  {
    id: "kb-stage-student",
    title: "Student guidance: Lead with education and deep technical projects",
    guidance:
      "For students without extensive professional software experience, place Education first, followed immediately by substantial Projects and Skills. Showcase end-to-end architecture, API integrations, and database design in projects rather than shallow homework assignments. Do not penalize students for lacking senior leadership or corporate metrics.",
    category: "career-stage",
    careerStages: ["student"],
    locale: "general",
    applicability: "general",
    tasks: ["build", "tailor", "format"],
    sections: ["projects", "education", "skills"],
    tags: ["student", "internship", "projects", "education", "coursework"],
    mandatory: false,
  },
  {
    id: "kb-stage-new-grad",
    title: "New Graduate guidance: Elevate internship experience",
    guidance:
      "For new grads with internship or co-op experience, place Experience before Projects. Highlight production code contributions, code reviews, and measurable sprint outcomes. Keep Education prominent near the top or immediately after Experience.",
    category: "career-stage",
    careerStages: ["new-graduate"],
    locale: "general",
    applicability: "general",
    tasks: ["build", "tailor", "format"],
    sections: ["experience", "education", "projects"],
    tags: ["new-grad", "internship", "graduation", "entry-level"],
    mandatory: false,
  },
  {
    id: "kb-stage-early-career",
    title: "Early Career guidance: Solidify professional deliverables",
    guidance:
      "For engineers with 1–3 years of experience, professional experience must dominate the resume. School projects should be phased out in favor of production software, architecture improvements, bug reductions, and feature ownership.",
    category: "career-stage",
    careerStages: ["early-career"],
    locale: "general",
    applicability: "general",
    tasks: ["build", "tailor"],
    sections: ["experience", "skills", "projects"],
    tags: ["early-career", "ownership", "production", "deliverables"],
    mandatory: false,
  },
  {
    id: "kb-stage-mid-level",
    title: "Mid-Level guidance: Demonstrate autonomy and system reliability",
    guidance:
      "For engineers with 4–7 years of experience, emphasize independent feature delivery, microservice architecture, API design, CI/CD, performance tuning, and cross-functional collaboration. Personal hobby projects should not displace impactful full-time employment.",
    category: "career-stage",
    careerStages: ["mid-level"],
    locale: "general",
    applicability: "general",
    tasks: ["build", "tailor"],
    sections: ["experience", "skills"],
    tags: ["mid-level", "autonomy", "systems", "scalability", "architecture"],
    mandatory: false,
  },
  {
    id: "kb-stage-senior",
    title: "Senior & Staff guidance: Focus on architectural scope and team multiplier",
    guidance:
      "For senior, staff, and principal engineers (8+ YoE), bullets should emphasize technical roadmap leadership, mentoring, architectural decisions, cross-team impact, and system reliability at scale. A concise 2–3 line executive summary is appropriate to frame senior domain expertise.",
    category: "career-stage",
    careerStages: ["senior", "staff-principal"],
    locale: "general",
    applicability: "general",
    tasks: ["build", "tailor"],
    sections: ["summary", "experience"],
    tags: ["senior", "staff", "principal", "scope", "leadership", "architecture"],
    mandatory: false,
  },
  {
    id: "kb-stage-career-changer",
    title: "Career Changer guidance: Frame transferable analytical strength",
    guidance:
      "For candidates transitioning into software engineering, use a concise 2–3 line summary to position their pivot. Lead with software projects, technical skills, and technical certifications. Frame prior non-SWE roles around quantitative problem-solving and domain knowledge without disguising them as software engineering roles.",
    category: "career-stage",
    careerStages: ["career-changer"],
    locale: "general",
    applicability: "general",
    tasks: ["build", "tailor"],
    sections: ["summary", "skills", "projects", "experience"],
    tags: ["career-changer", "pivot", "transferable", "transition"],
    mandatory: false,
  },
  {
    id: "kb-stage-returning",
    title: "Returning Professional guidance: Contextual framing and fresh technical signal",
    guidance:
      "For engineers returning after an employment gap, use an objective summary or clear date framing. Surface recent projects, open-source contributions, or modern certifications to demonstrate current tooling fluency.",
    category: "career-stage",
    careerStages: ["returning-professional"],
    locale: "general",
    applicability: "general",
    tasks: ["build", "tailor"],
    sections: ["summary", "experience", "skills", "projects"],
    tags: ["gap", "returning", "currency", "upskilling"],
    mandatory: false,
  },
];
